# Planifier un cronjob chaque jour à 10h
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraping-job
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraping-container
            image: src-scraping
            command: ["python", "/app/cronjobs/scraping_cronjob.py"]  # Ajout de la commande pour exécuter le script Python
          restartPolicy: OnFailure
