version: '3'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile_elasticsearch
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    build:
      context: .
      dockerfile: Dockerfile_kibana
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  scraping:
    build:
      context: .
      dockerfile: Dockerfile_scraping
    volumes:
      - ./data:/app/data
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
