FROM python:3.8

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the cronjob script
COPY cronjob_script.py .

# Expose any necessary ports
# EXPOSE 8000

# Command to run on container start
CMD ["python", "cronjob_script.py"]
